### ISSUE TITLE
Hard crash when right clicking Grass blocks with shovels

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/vanilla-tools#20]
Hi guys,

Encountered a hard crash when playing on Valhelsa 3.

Crashed when attempting to right click on grass block with shovel.

Any ideas?

Currently using version: 1.16.5-4.2

[01Apr2021 21:33:43.250] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method net.minecraft.item.ShovelItem.func_220041_a(Lnet/minecraft/item/ItemUseContext;Lnet/minecraft/entity/player/PlayerEntity;)V from class com.ldtteam.supertools.items.ShovelSuperTools
	at com.ldtteam.supertools.items.ShovelSuperTools.func_195939_a(ShovelSuperTools.java:59) ~[supertools:1.16.5-4.2]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:643) ~[forge:?]
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:121) ~[apotheosis:4.4.1]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:353) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.item.ShovelItem.func_220041_a(Lnet/minecraft/item/ItemUseContext;Lnet/minecraft/entity/player/PlayerEntity;)V from class com.ldtteam.supertools.items.ShovelSuperTools
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_282]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_282]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_282]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_282]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_282]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_282]
	... 22 more

**Comment by ravenbuilder934** [comment]
Yeah I looked into this a bit but couldn't find a way to reproduce it. If you do lmk

**Comment by Aduis1210** [comment]
Shall do raven - any particular evidence you need?

**Comment by ravenbuilder934** [comment]
Hmm. Maybe if you're on a server, singleplayer game, or open to LAN game

**Comment by Aduis1210** [comment]
i've got my own server? we are using a modified version of Valesha three with up dated minecolonies

**Comment by ravenbuilder934** [comment]
Oh, also, can you try 4.3? Changelog just says it removes the searchbar, but also has some backend stuff

**Comment by Aduis1210** [comment]
Course :) ill update and let you know

**Comment by Pockyman1** [comment]
https://gist.github.com/Pockyman1/bbc2f3b60a6151d6d1a04ae942145221 recreated similar issue also running a personal server between 2 ppl

**Comment by Aduis1210** [comment]
@ravenbuilder934 same issue on updated version :(

**Comment by ravenbuilder934** [comment]
I made a server and used that to test, still didn't crash. Hmm

**Comment by Pockyman1** [comment]
When you tested it did you have a colony up already ? Cause I had a colony up by then when I got the crash ? although I haven't tested before hand since didn't need the pathways yet.

**Comment by ravenbuilder934** [comment]
No, in fact I didn't even have minecolonies installed. I'll try with a colony, though I don't see why that would cause it

**Comment by Pockyman1** [comment]
Well it could be in correlation to how the colonists use that pathway as their way of changing their pathways when traveling from place to place is all I can really think of

**Comment by Aduis1210** [comment]
I have a theory. Do you have quark installed?

**Comment by ravenbuilder934** [comment]
okay, so apparently it crashes when
- you're on a server
- either minecolonies or quark are installed (possibly both? might need a colony?)
- you use a VPT shovel to make path blocks

this is officially the weirdest bug I've encountered

**Comment by Pockyman1** [comment]
Ok just loaded up a fresh server without a Colony setup at alll anywhere and use the VPT shovel to make a path and crash instantly 
https://gist.github.com/Pockyman1/001dd7b18759edeef9b0efcd28b7385a

Also Scratch that I just loaded the game in a singgle player nonserver and used the vpt shovel to make a path and it crashed my game

**Comment by ravenbuilder934** [comment]
okay, then maybe it's not the server, but the mods. what other mods did you have besides VPT?

**Comment by Pockyman1** [comment]
All the mods thats on the pack are basically the Official Minecolonies  pack thats on the GD launcher or as its listed Minecolonies  Official is the name all i did was turn off 3 mods on my end which is the BYG mod, Horsestandstill, Bettercaves, are  either turned off or deleted. there are 2-4 mods on the pack that affect tools which to me i realize are useless  but haven't turned off till now which is the Ding, durability 101, durability viewer. will turn those off and see if there is any change

**Comment by ravenbuilder934** [comment]
can you also try turning off minecolonies and quark?

**Comment by Pockyman1** [comment]
I can try with Minecolonies but Quark is not on the list unless its under a different name but Quark doesn't show up on mod list

**Comment by Pockyman1** [comment]
Sooo Still Crashed with minecolonies turned off

**Comment by ravenbuilder934** [comment]
does it crash with *no* other mods?

**Comment by Pockyman1** [comment]
![image](https://user-images.githubusercontent.com/81746239/113514343-d3d04300-9522-11eb-89d1-ae65cabc68f3.png)

**Comment by ravenbuilder934** [comment]
can you find the actual crash report in the instance/crashreports folder?

**Comment by Pockyman1** [comment]
[crash-2021-04-04_08.53.57-server.txt](https://github.com/ldtteam/vanilla-tools/files/6254884/crash-2021-04-04_08.53.57-server.txt)

**Comment by Pockyman1** [comment]
https://gist.github.com/Pockyman1/988444cd5196d0463b34f4f7a23c46d6

**Comment by ravenbuilder934** [comment]
that still has lots of mods, can you try with only VPT?

**Comment by Pockyman1** [comment]
unfortunately I can't test that right now its actually pretty late for me

**Comment by ravenbuilder934** [comment]
that's fine, whenever you can :D

**Comment by Pockyman1** [comment]
well ok VPT itself is causing the crash

**Comment by Pockyman1** [comment]
WORKS PErfectly Fine when you downgrade the VPT mod to the February update anything after that crashes the game

**Comment by ravenbuilder934** [comment]
okay I managed to reproduce it, but only when not in a dev env.
