### ISSUE TITLE
still crashing client when launching 1.14.4

### ISSUE THREAD

**Issue by raziel23x** [ldtteam/vanilla-tools#6]
[20:41:28] [main/INFO]: ModLauncher running: args [--username, raziel23x, --version, forge-28.0.20, --gameDir, F:\Curse\Minecraft\Instances\1.14.4, --assetsDir, F:\Curse\Minecraft\Install\assets, --assetIndex, 1.14, --uuid, 759c61a801584a91985aac7d128bb211, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 28.0.20, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190719.225934]
[20:41:28] [main/INFO]: ModLauncher 3.1.0+58+1395384 starting: java version 1.8.0_51 by Oracle Corporation
[20:41:31] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: Duplicate key net.minecraftforge.fml.loading.moddiscovery.ModFileInfo@6692b6c6
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.Collectors.lambda$throwingMerger$113(Collectors.java:133)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.Collectors$$Lambda$14/1439337960.apply(Unknown Source)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.merge(HashMap.java:1245)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.Collectors.lambda$toMap$171(Collectors.java:1320)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.Collectors$$Lambda$16/631659383.accept(Unknown Source)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.LoadingModList.<init>(LoadingModList.java:60)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.LoadingModList.of(LoadingModList.java:66)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.ModSorter.sort(ModSorter.java:77)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:83)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:202)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:90)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:107)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:112)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$143/1464555023.accept(Unknown Source)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:112)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[20:41:33] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by raziel23x** [comment]
more changes to the forge API needs another look at Vanilla+ Tools-1.14.4-2.1 as this mod is not allowing client to load currently running latest version of forge 1.14.41.14.4-28.0.40

**Comment by Raycoms** [comment]
Working on it

**Comment by Raycoms** [comment]
Fixed
